Algoritmo "EX2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/02/2026
Var
i : inteiro
numeros : vetor[1..10] de inteiro

Inicio
i <- 1
enquanto ( i <= 10 )faca
  leia(numeros[i])
 i <- i + 1
fimEnquanto

i <- 10
enquanto ( i > 0 )faca
  escreval(numeros[i])
 i <- i - 1
fimEnquanto

Fimalgoritmo